version: "3"

networks:
  blog-network:

services:
  app:
    build: app
    networks:
      blog-network:
    environment:
      - APP_API=http://api:5000

  api:
    build: api
    networks:
      blog-network:
    volumes:
      - ./api/posts:/app/posts

  nginx:
    build: nginx
    ports:
      - 3000:80
    networks:
      blog-network:
