version: "3"

networks:
  blog-network:

services:
  app:
    build:
      context: packages/app
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/app:/app
      - /app/node_modules/
    networks:
      - blog-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API=http://api:5000
    depends_on:
      - api

  api:
    build:
      context: packages/api
      dockerfile: Dockerfile.dev
    networks:
      - blog-network
    volumes:
      - ./packages/api:/app
      - /app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build: packages/nginx
    ports:
      - 8080:80
    networks:
      - blog-network
    depends_on:
      - app
      - api
