version: "3.4"

networks:
  blog-network:
  traefik-proxy:
    external: true
services:
  app:
    build: 
      context: packages/app
    restart: unless-stopped
    networks:
      - blog-network

  api:
    build: 
      context: packages/api
    restart: unless-stopped
    networks:
      - blog-network
    volumes:
      - /data/posts:/app/posts

  nginx:
    build: 
      context: packages/nginx
    restart: unless-stopped
    networks:
      - blog-network
      - traefik-proxy
    volumes:
      - /docker/log/nginx-${DEPLOY_ENV}/access.log:/var/log/nginx/access.log
      - /docker/log/nginx-${DEPLOY_ENV}/error.log:/var/log/nginx/error.log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DEPLOY_ENV}.rule=Host(`grimbakor.com`)"
      - "traefik.http.routers.${DEPLOY_ENV}.tls=true"
      - "traefik.http.routers.${DEPLOY_ENV}.tls.certresolver=le-resolver"
      - "traefik.docker.network=traefik-proxy"


