version: "3.4"

networks:
  blog-network:
  traefik-proxy:
    external: true
services:
  app:
    build: 
      context: packages/app
      network: host
    networks:
      - blog-network

  api:
    build: 
      context: packages/api
      network: host
    networks:
      - blog-network
    volumes:
      - /data/posts:/app/posts

  nginx:
    build: 
      context: packages/nginx
      network: host
    networks:
      - blog-network
      - traefik-proxy
    volumes:
      - /docker/log/nginx-blog/access.log:/var/log/nginx/access.log
      - /docker/log/nginx-blog/error.log:/var/log/nginx/error.log
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`grimkor.tech`)"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=le-resolver"
      - "traefik.docker.network=traefik-proxy"


