FROM node:14-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm i
RUN npm install nodemon -g --silent

COPY . ./

EXPOSE 5000

USER node

CMD ["nodemon", "npm", "--", "start"]
